# Fun with numpy.random
Exploring numpy.random library as assignment for Programming for Data Analysis, GMIT 2019

Lecturer: dr Brian McGinley

>Author: **Andrzej Kocielski**  
>Github: [andkoc001](https://github.com/andkoc001/)  
>Email: G00376291@gmit.ie, and.koc001@gmail.com

Created: 11-10-2019

This Notebook should be read in conjuntion with the corresponding README.md file at the assignment repository at GitHub: <https://github.com/andkoc001/fun-with-numpy-random/>, which provides background information, project progress and findings.

___

## Setting up the scene

Importing numpy.random library and version check.

In [1]:
import numpy as np

In [3]:
np.version.version

'1.17.2'

A built-in help is available, accessible through the following commands:  
`dir()` prints out available funtionalitis of the parsed method  
`help()` shows doc-string of the parsed method

In [8]:
# dir(np.random) # commented out for clarity

In [12]:
# help(np.random.randint) # commented out for clarity

A quick test of the numpy.random routine.

In [2]:
np.random.random() # get a random float number from *uniform distributtion* on [0,1)

0.8012793231416243

Note: In this notebook terms _funtion_, _method_ and _subroutine_ are used interchangebly. 

## Random Sampling

NumPy comes with a large numbers of built-in funtionalities, in the library documentation refered as to routines. Random sampling (`numpy.random`) is an example of such a routine (function). 

### Simple random data

**Simple random data** is a collection of methods used for two applications:  
1) generating of a pseudo random number from a range,  
2) random selection of an object from a list.

In the first category, there are several methods, producing different outputs. For instance, the `np.random.random()` generates float numbers from half-open range [0,1), whereas `np.random.randint()` generates integer numbers from a range.

The second category, offers the funtionality of random picking of objects from an existing list. 

Below we will see example use of a few methods from the Simple random data.

**np.random.random**  
This method returns random float number(s) from _uniform distribution_ on [0,1), i.e. from 0 (inclusive) to 1 (exclusive)

In [14]:
# get a random float number from *uniform distributtion* on [0,1), i.e. from 0 (inclusive) to 1 (exclusive)
np.random.random()

0.8168828453846011

In [ ]:
# get 5 random numbers from [0,1) and print out avarage of them
sum = 0
for i in range(5):
    x = np.random.random()
    sum = sum + x
    print(i+1,": ",x)
print("Average:",sum/5)

In [44]:
# get a n-dimensional array (ndarray) of random numbers on [0,1); when no value is parsed, it returns a simple float number
np.random.random((2,3)) # double brackets, because this method takes a single value only - in this case a tuple

array([[0.73519204, 0.83011869, 0.49265245],
       [0.20173093, 0.24926521, 0.55214405]])

**np.random.randn**  
This method generates a n-dimmensional array of numbers from the _standard normal distribution_(including negative).

In [33]:
np.random.randn(2, 4)

array([[ 0.93138901, -0.4730313 , -0.0271327 ,  1.82534732],
       [ 0.65415303,  1.26116489, -1.25606514, -0.65206399]])

**np.random.randint**  
This method generates intiger number(s) in a given range.

In [43]:
np.random.randint(1,11, size=3) # 3 random integers in range (1,10) - inclusive

array([9, 6, 5])

In the second category of subroutines of simple random data, from a pre-defined pool of objects.

**np.random.choice**  
This method returns items (not necesserily numbers) from an existing list.

In [71]:
list_1 = [1,2,3,4] # predefinition of list of numbers
list_2 = ["dog", "cat", "snake", "rat"] # predefinition of list of animals

np.random.choice(list_2, size=7)

array(['dog', 'dog', 'rat', 'cat', 'rat', 'dog', 'rat'], dtype='<U5')

It is also possible to assign a probability for each option:

In [70]:
np.random.choice(list_1, p=[0.1, 0.1, 0.1, 0.7], size=10)

array([4, 4, 4, 4, 4, 4, 3, 4, 4, 4])

### Permutations

**np.random.permutation**  
This method returns the objects from a list in a new, random order.random

In [72]:
np.random.permutation(list_1)

array([1, 4, 2, 3])