# fun-with-numpy-random - sandbox
Exploring numpy.random library - a temporary test ground.

Programming for Data Analysis, GMIT 2019

Lecturer: dr Brian McGinley

>Author: **Andrzej Kocielski**  
>Github: [andkoc001](https://github.com/andkoc001/)  
>Email: G00376291@gmit.ie, and.koc001@gmail.com

Created: 16-10-2019

## Set up

In [3]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd  
import seaborn as sns 

# This allows the plots being displayed inside the notebook, rather than in a separate screen.
%matplotlib inline

## Random sampling

### Simple random data

Note `np.random.random` is an alias for `np.random.random_sample`

In [4]:
# get a random float number from *uniform distributtion* on [0,1)
np.random.random()

0.5776462717523824

In [32]:
# get 5 random numbers from 0 (inclusive) to 1 (exclusive)
for i in range(5):
    print(np.random.random())

0.3655681049534232
0.7564954202713843
0.09291827122045726
0.9943987954176662
0.7653433788570845


In [65]:
# get 5 random numbers from 0 (inclusive) to 1 (exclusive) and print out avarage of them
sum = 0
for i in range(5):
    x = np.random.random()
    sum = sum + x
    print(i+1,": ",x)
print("Average:",sum/5)

1 :  0.2342369587659341
2 :  0.12594289707682726
3 :  0.1754210620824853
4 :  0.05062503371133742
5 :  0.3586711931911424
Average: 0.1889794289655453


In [81]:
# get 5 random numbers [0,1) arranged in an array
np.random.random_sample(5)

array([0.44313538, 0.59712914, 0.6448731 , 0.17447487, 0.38135937])

In [76]:
# get an array (shaped with 2 rows and 3 columns) of random numbers
np.random.random((2,3)) # double brackets, because this method takes a single value only - in this case a tupel

array([[0.92378228, 0.19388332, 0.99883698],
       [0.06926746, 0.67068679, 0.50861555]])

In [77]:
a = np.random.random((2,3))
type(a)

numpy.ndarray

In [89]:
# the same result as above, can be achieved using np.random.rand() - reference: https://stackoverflow.com/a/47232184
# get an array (shaped with 2 rows and 3 columns) of random numbers
np.random.rand(2,3) #  With numpy.random.rand, the length of each dimension of the output array is a separate argument.

array([[0.07051494, 0.77203962, 0.96662263],
       [0.3041466 , 0.07015579, 0.5948823 ]])

In [84]:
# help(np.random.randint)

In [58]:
a = np.random.randint(4, size=8)
a
# type(a)

array([1, 3, 1, 2, 0, 0, 3, 0])

In [62]:
b = np.random.randint(0, 4, (1,8))
b
# type(b)

array([[3, 0, 2, 1, 3, 2, 3, 3]])

In [63]:
np.random.randint(0,4, (8,1))

array([[3],
       [3],
       [0],
       [0],
       [2],
       [1],
       [0],
       [1]])

**Simple random data:**  
rand(d0, d1, ..., dn) Random values in a given shape.  
randn(d0, d1, ..., dn) Return a sample (or samples) from the “standard normal” distribution.  
randint(low[, high, size, dtype]) Return random integers from low (inclusive) to high (exclusive).  
random_sample([size]) Return random floats in the half-open interval [0.0, 1.0).  
random([size]) Return random floats in the half-open interval [0.0, 1.0).  
ranf([size]) Return random floats in the half-open interval [0.0, 1.0).  
sample([size]) Return random floats in the half-open interval [0.0, 1.0).  
choice(a[, size, replace, p]) Generates a random sample from a given 1-D array  
bytes(length) Return random bytes.  

In [127]:
np.random.randint(1-5,3, size=10)

array([ 2, -4, -1, -3,  1,  2,  0, -1, -2,  0])

In [163]:
np.random.ranf(3)

array([0.4283522 , 0.72563786, 0.94239311])

In [159]:
np.random.random((2,3))

array([[0.66638091, 0.281811  , 0.470344  ],
       [0.31593002, 0.35025994, 0.9672781 ]])

In [15]:
np.random.random((2,2,2,2,2))

array([[[[[0.93235262, 0.3039091 ],
          [0.50304157, 0.06080845]],

         [[0.24188326, 0.37909191],
          [0.94094891, 0.14109456]]],


        [[[0.74097979, 0.9718632 ],
          [0.05811432, 0.5600528 ]],

         [[0.5213372 , 0.34714916],
          [0.25054188, 0.41448392]]]],



       [[[[0.78760414, 0.1886975 ],
          [0.29335798, 0.40397248]],

         [[0.04509335, 0.09948334],
          [0.29738838, 0.50418824]]],


        [[[0.73594875, 0.82157702],
          [0.46727867, 0.82278829]],

         [[0.45788953, 0.39551272],
          [0.67452259, 0.27006429]]]]])

In [16]:
type(np.random.randint(1,11, size=3))

numpy.ndarray

In [24]:
np.random.bytes(10)

b'\xeb\x12\xe9\xa2\x9e0fd+u'