# fun-with-numpy-random - sandbox
Exploring numpy.random library - a temporary test ground.

Programming for Data Analysis, GMIT 2019

Lecturer: dr Brian McGinley

>Author: **Andrzej Kocielski**  
>Github: [andkoc001](https://github.com/andkoc001/)  
>Email: G00376291@gmit.ie, and.koc001@gmail.com

Created: 16-10-2019

## Set up

In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd  
import seaborn as sns 

# This allows the plots being displayed inside the notebook, rather than in a separate screen.
%matplotlib inline

## Getting data points

Testing numpy.random package

Note `np.random.random` is an alias for `np.random.random_sample`

In [80]:
# get a random float number from *uniform distributtion* on [0,1)
np.random.random()

0.9326986012131828

In [32]:
# get 5 random numbers from 0 (inclusive) to 1 (exclusive)
for i in range(5):
    print(np.random.random())

0.3655681049534232
0.7564954202713843
0.09291827122045726
0.9943987954176662
0.7653433788570845


In [65]:
# get 5 random numbers from 0 (inclusive) to 1 (exclusive) and print out avarage of them
sum = 0
for i in range(5):
    x = np.random.random()
    sum = sum + x
    print(i+1,": ",x)
print("Average:",sum/5)

1 :  0.2342369587659341
2 :  0.12594289707682726
3 :  0.1754210620824853
4 :  0.05062503371133742
5 :  0.3586711931911424
Average: 0.1889794289655453


In [81]:
# get 5 random numbers [0,1) arranged in an array
np.random.random_sample(5)

array([0.44313538, 0.59712914, 0.6448731 , 0.17447487, 0.38135937])

In [88]:
# get an array (shaped with 2 rows and 3 columns) of random numbers
np.random.random((2,3)) # double brackets, because this method returns tupels as default

array([[0.42188078, 0.32940493, 0.25277206],
       [0.8919418 , 0.89354237, 0.36036188]])

In [89]:
# the same result as above, can be achieved using np.random.rand() - reference: https://stackoverflow.com/a/47232184
# get an array (shaped with 2 rows and 3 columns) of random numbers
np.random.rand(2,3) #  With numpy.random.rand, the length of each dimension of the output array is a separate argument.

array([[0.07051494, 0.77203962, 0.96662263],
       [0.3041466 , 0.07015579, 0.5948823 ]])